### ISSUE TITLE
spint-backlog: Tìm hiểu công nghệ

### ISSUE THREAD

**Issue by buibaouet** [buibaouet/INT2208-7-2019#17]
-Học HTML
-Học CSS
-Học Bootstrap
-Học NodeJS
-Học JavaScript
-Học SQL

**Comment by traidat** [comment]
- [ ]  Học HTML
 
- [ ] Học CSS 

- [ ]  Học NodeJS

- [ ]  Học JavaScript

- [ ]  Học SQL
